/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "car": {
        "CAR-0001": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
    };
    "order": {
        "ORD-0001": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "ORD-0002": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "ORD-0003": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "ORD-0004": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "ORD-0005": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "ORD-0006": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
    };
    "promo": {
        "PRO-0001": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "PRO-0002": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "PRO-0003": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
    };
    "system": {
        "CUS-0001": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "CUS-0602": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "CUS-0603": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
    };
    "token": {
        "TOK-0001": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
    };
    "user": {
        "CUS-0403": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "USE-0001": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "USE-0002": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "USE-0003": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "USE-0006": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "USE-0007": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
        "CUS-0405": {
            "http_code": string;
            "app_code": string;
            "title": string;
            "prod": string;
            "inter": string;
        };
    };
};
export type I18nPath = Path<I18nTranslations>;
